### ISSUE TITLE
work out how to do environment variables in elixir

### ISSUE THREAD

**Issue by ZooeyMiller** [ZooeyMiller/phoenix-elixir-todos#22]
At the moment we have environment variables we're accessing by using `System.get_env/1` but we're only setting the environment variables by using the `source <env file>` bash command, but this has to be re-run any time the terminal is restarted etc. It would be preferable to having something akin to `env2` in node such that our environment variables are automatically created.

**Comment by finnhodgkin** [comment]
With the help of lovely Andrew we have now moved to using the Envy module to import our environment variables.

For future reference, here's the less good method used before:

### environment variables

You will need to create a config.env file in the root of the project, inside you will need to put:

```
export GITHUB_SECRET=<your secret key here>
export GITHUB_CLIENT_ID=<your client id here>
```

then before you run the code for the first time run `source config.env` in your terminal, and you'll be good to go!

**Comment by finnhodgkin** [comment]
Took a lot less than an hour :smile:
