### ISSUE TITLE
get a single todo list displaying

### ISSUE THREAD

**Issue by ZooeyMiller** [ZooeyMiller/phoenix-elixir-todos#5]
thanks to all the lovely templating stuff, if we get a single todo list with a basic list of todos displaying, then we can use this as a basis for expanding it later

**Comment by ZooeyMiller** [comment]
We're having some trouble getting acquainted with the way everything works in 1.3, and where to put our database logic and stuff. We've made our migration but now we need to get our controller set up and we're just not sure where to put things. 

We're asking @andrewmacmurray for any info he may have an example of a 1.3 app we could look at.

**Comment by andrewMacmurray** [comment]
@ZooeyMiller it's a mini example but we used it on the action for children project: https://github.com/cast-fuse/action-for-children

**Comment by ZooeyMiller** [comment]
After a suggeestion from @ivanmauricio we've move to using `phx.gen.html` rather  than `phx.gen.schema` and our lives are a loooooot easier now.

**Comment by finnhodgkin** [comment]
IT DOES EVERYTHING :astonished:

**Comment by finnhodgkin** [comment]
Because phx.gen.html does everything automatically it took substantially less than 4 hours to add this feature, plus #6 #7 #8. Phoenix is great :heart: :heart_eyes: :heart_eyes_cat:
